config/routes.rb
Agilityperu::Application.routes.draw do

  resources :jueces

  get 'ubicacion/editar_ubicacion'

  put 'ubicacion/update_ubicacion'

  get '/ubicacion' => 'ubicacion#index'

  get 'tags/:tag', to: 'duplas#index', as: :tag

  resources :costos

  resources :reglamentos

  resources :guias

  resources :duplas

  resources :programas

  resources :organizadores

  resources :contactos

  resources :streamings

  resources :requisitos

  resources :transportes

  resources :hoteles

  resources :visas

  resources :mensajes

  resources :noticias

  resources :auspiciadores

  resources :slides

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  devise_for :usuarios, :controllers => { :registrations => "usuarios/registrations" }, :path => "usuarios", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  resources :usuarios do
    resources :duplas
  end

  root to: 'inicio#index'
  get "inicio/index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auspiciador.rb
class Auspiciador < ActiveRecord::Base
  mount_uploader :imagen, LogoUploader
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/dupla.rb
require 'csv'

class Dupla < ActiveRecord::Base

  default_scope  { order("created_at DESC") }

  mount_uploader :fotografia, FotografiaUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |dupla|
        csv << dupla.attributes.values_at(*column_names)
      end
    end
  end
  belongs_to :usuario
  has_many :guias
  accepts_nested_attributes_for :guias

  acts_as_taggable

  #paginates_per 5

  before_save :override_tag

  def override_tag
    self.tag_list << self.pais
  end
  validates :nombre, presence: true
  validates :registro_genealogico, presence: true
  validates :raza, presence: true
  validates :color, presence: true
  validates :categoria, presence: true
  validates :grado, presence: true
  validates :fotografia, presence: true



end

app/models/guia.rb
class Guia < ActiveRecord::Base

  belongs_to :dupla
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/juez.rb
class Juez < ActiveRecord::Base
  mount_uploader :foto, FotografiaUploader
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base

  validates :nombre, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
  validates :mensaje, presence: true

end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  mount_uploader :foto, FotoUploader

  default_scope  { order("fecha DESC") }

  def noticia_anterior
    self.class.first(:conditions => ["id < ?", id], :order => "id desc")
  end

  def siguiente_noticia
    self.class.first(:conditions => ["id > ?", id], :order => "id asc")
  end
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
end

app/models/programa.rb
class Programa < ActiveRecord::Base
end

app/models/reglamento.rb
class Reglamento < ActiveRecord::Base
end

app/models/requisito.rb
class Requisito < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :imagen, SlideUploader
end

app/models/streaming.rb
class Streaming < ActiveRecord::Base
end

app/models/transporte.rb
class Transporte < ActiveRecord::Base
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  mount_uploader :imagen1, FotografiaUploader
  mount_uploader :imagen2, FotografiaUploader
  mount_uploader :imagen3, FotografiaUploader
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :duplas

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :ciudad, presence: true
end

app/models/visa.rb
class Visa < ActiveRecord::Base
  mount_uploader :imagen, ImagenUploader
end

app/controllers/duplas_controller.rb
class DuplasController < InheritedResources::Base
  before_filter :authenticate_usuario!, only: [:new, :create]

  belongs_to :usuario

  before_filter :setup_usuario

  def permitted_params
    params.permit(:dupla => [:nombre, :pais, :registro_genealogico, :raza, :color, :sexo, :categoria, :grado, :tatuaje_microchip, :especial_g1, :open_ac, :ac_oficial, :fotografia, :fecha_nacimiento, :usuario_id, guias_attributes: [:id, :nombre, :apellido, :direccion, :telefono, :email, :_destroy]])
  end

  def index
    @tags = Dupla.tag_counts_on(:tags)
    if params[:usuario_id]
      @duplas = Dupla.where("usuario_id = ?", @usuario.id)
    else
      if params[:tag]
        @duplas = Dupla.tagged_with(params[:tag])
      else
        @duplas = Dupla.all
      end
    end
    respond_to do |format|
      format.html
      format.js {}
      format.csv { send_data  @duplas.to_csv}
      format.xls
      format.json { render json: @duplas }
    end
  end

  def new
    redirect_to inicio_index_path, notice: "Ya se Cerro la Inscripción"
  end

  def setup_usuario
    if current_usuario
      @usuario = Usuario.find(current_usuario.id)
    else
      if params[:usuario_id]
        @usuario = Usuario.find(params[:usuario_id])
      end
    end
  end

  def mis_duplas
    @duplas = Dupla.where("usuario_id = ?", @usuario.id)
    respond_to do |format|
      format.html
      format.js {}
      format.json { render json: @duplas }
    end
  end
  def create
    create!( notice: "Dupla creada con éxito."){ usuario_duplas_path(@usuario) }
  end

  def update
    update!( notice: "La dupla ha sido editada."){ usuario_duplas_path(@usuario) }
  end

  def destroy
    destroy!( notice: "La dupla ha sido eliminada."){ usuario_duplas_path(@usuario) }
  end
end

app/helpers/duplas_helper.rb
module DuplasHelper
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/views/duplas/_fci2doperro.html.erb
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='5'>
  <input name='submit' type='submit' value='FCI + Open 2do perro'  class="btn btn-warning" >
  </form>

app/views/duplas/_fci3erperro.html.erb
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='6'>
  <input name='submit' type='submit' value='FCI + Open 3er perro' class="btn btn-warning" >
  </form>

app/views/duplas/_fciopen.html.erb
  <form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='3'>
  <input name='submit' type='submit' value='FCI + Open' class="btn btn-warning">
  </form>

app/views/duplas/_form.html.haml
- content_for :javascript do
  = javascript_include_tag 'duplas.js'
  = javascript_include_tag 'nested_form.js'

= nested_form_for [@usuario, @dupla], :html => { class: 'form-horizontal', role: 'form', :multipart => true } do |f|
  - if @dupla.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dupla.errors.count, "error")}"
      %ul
        - @dupla.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :nombre, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :nombre, class: 'form-control'
  .form-group
    = f.label :pais, class: 'col-sm-2 control-label'
    .col-sm-10
      = country_select("dupla", "pais")
  .form-group
    = f.label :registro_genealogico, "Registro Genealógico", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :registro_genealogico, class: 'form-control'
  .form-group
    = f.label :raza, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :raza, class: 'form-control'
  .form-group
    = f.label :color, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :color, class: 'form-control'
  .form-group
    = f.label :sexo, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.label :sexo, "Macho"
      = f.radio_button :sexo, "Macho"
      = f.label :sexo, "Hembra"
      = f.radio_button :sexo, "Hembra"
  .form-group
    = f.label :fecha_nacimiento, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.date_select :fecha_nacimiento, start_year: 2000, end_year: 2014, class: 'form-control'
  .form-group
    = f.label :categoria, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.label :categoria, "Small"
      = f.radio_button :categoria, "Small"
      = f.label :categoria, "Medium"
      = f.radio_button :categoria, "Medium"
      = f.label :categoria, "Large"
      = f.radio_button :categoria, "Large"
  .form-group
    = f.label :grado, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.label :grado, "G1"
      = f.radio_button :grado, "G1"
      = f.label :grado, "G2"
      = f.radio_button :grado, "G2"
      = f.label :grado, "G3"
      = f.radio_button :grado, "G3"
  .form-group
    = f.label :tatuaje_microchip,"Tatuaje/Microchip", class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :tatuaje_microchip, class: 'form-control'
  .form-group
    = f.label :prueba, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.label :especial_g1, "Especial G1"
      = f.check_box :especial_g1
      = f.label :open_ac, "Open A&C"
      = f.check_box :open_ac
      = f.label :ac_oficial, "A&C Oficial"
      = f.check_box :ac_oficial
  .form-group
    = f.label :fotografia, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :fotografia
      %span#span_size
        (460px x 460px MÌNIMO)
  .form-group
    = f.label 'Guias / Guia Suplente', class: 'col-sm-2 control-label'
    .col-sm-8
      = f.fields_for :guias do |guia_form|
        = guia_form.text_field :nombre, placeholder: "Nombre", class: 'form-control'
        %br
        = guia_form.text_field :apellido, placeholder: "Apellido", class: 'form-control'
        %br
        = guia_form.text_field :direccion, placeholder: "Direccion", class: 'form-control'
        %br
        = guia_form.text_field :telefono, placeholder: "Telefono", class: 'form-control'
        %br
        = guia_form.text_field :email, placeholder: "Email", class: 'form-control'
        %br
        = guia_form.link_to_remove "Eliminar Guia", class: 'btn btn-danger'
        %br
      = f.link_to_add "Agregar Guia", :guias, class: 'btn btn-primary'
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/duplas/_grado1.html.erb
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='2'>
  <input name='submit' type='submit' value='Comprar Grado 1' class="btn btn-warning" >
</form>
<span>2Checkout.com Inc. (Ohio, USA) is a payment facilitator for goods and services provided by KENNEL CLUB PERUANO.</span>

app/views/duplas/_open.html.erb
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='4'>
  <input name='submit' type='submit' value='Open' class="btn btn-warning">
  </form>

app/views/duplas/_open2doperro.html.erb
<form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='7'>
  <input name='submit' type='submit' value='Open 2do perro' class="btn btn-warning" >
  </form>

app/views/duplas/_open3erperro.html.erb
  <form action='https://www.2checkout.com/checkout/purchase' method='post'>
  <input type='hidden' name='sid' value='202215395'>
  <input type='hidden' name='quantity' value='1'>
  <input type='hidden' name='product_id' value='8'>
  <input name='submit' type='submit' value='Open 3er perro' class="btn btn-warning" >
  </form>

app/views/duplas/edit.html.haml
- page_title!('Editando dupla')

#region-duplas.container.seccion

  .region
    .region-title
      %h1
        Editando
        %b
          dupla

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/duplas/index.html.haml
#region-duplas.container.seccion

  .region
    .region-title
      %h1= page_title!('duplas')

    .region
      -# if current_usuario
        .admin-control
          =# link_to 'Inscribir una Nueva Dupla', new_dupla_path, class: 'btn btn-primary'
    - if current_admin
      .region
        .descarga
          =# link_to "CSV", duplas_path(format: "csv"), class: 'btn btn-warning'
          = link_to "Descargar Todas las duplas en Excel", duplas_path(format: "xls"), class: 'btn btn-warning'

    .region-inner.sidebar.region-title
      - unless params[:usuario_id]
        %h2.title Paises
        - @tags.each do |tag|
          = link_to tag.name, tag_path(tag.name), class: 'btn btn-warning'
        = link_to "Todos", duplas_path, class: 'btn btn-warning'

  .region
    #duplas
      .region
        = render @duplas

app/views/duplas/index.js.erb
$("#duplas").html("<%= escape_javascript(render(@duplas)) %>");

app/views/duplas/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
      <Table>
        <Row>
          <Cell><Data ss:Type="String">ID</Data></Cell>
          <Cell><Data ss:Type="String">Fecha Inscripcion</Data></Cell>
          <Cell><Data ss:Type="String">Nombre</Data></Cell>
          <Cell><Data ss:Type="String">Pais</Data></Cell>
          <Cell><Data ss:Type="String">N Registro</Data></Cell>
          <Cell><Data ss:Type="String">Raza</Data></Cell>
          <Cell><Data ss:Type="String">Color</Data></Cell>
          <Cell><Data ss:Type="String">Sexo</Data></Cell>
          <Cell><Data ss:Type="String">Fecha Nacimiento</Data></Cell>
          <Cell><Data ss:Type="String">Categoria</Data></Cell>
          <Cell><Data ss:Type="String">Grado</Data></Cell>
          <Cell><Data ss:Type="String">Chip/Tatuaje</Data></Cell>
          <Cell><Data ss:Type="String">Especial G1</Data></Cell>
          <Cell><Data ss:Type="String">Open AC</Data></Cell>
          <Cell><Data ss:Type="String">AC Oficial</Data></Cell>
          <Cell><Data ss:Type="String">Nombre</Data></Cell>
          <Cell><Data ss:Type="String">Apellido</Data></Cell>
          <Cell><Data ss:Type="String">Direccion</Data></Cell>
          <Cell><Data ss:Type="String">Ciudad</Data></Cell>
          <Cell><Data ss:Type="String">Pais</Data></Cell>
          <Cell><Data ss:Type="String">Telefono</Data></Cell>
          <Cell><Data ss:Type="String">Email</Data></Cell>
          <Cell><Data ss:Type="String">Nombre</Data></Cell>
          <Cell><Data ss:Type="String">Apellido</Data></Cell>
          <Cell><Data ss:Type="String">Direccion</Data></Cell>
          <Cell><Data ss:Type="String">Telefono</Data></Cell>
          <Cell><Data ss:Type="String">Email</Data></Cell>
        </Row>
        <% @duplas.each do |dupla| %>
        <Row>
          <Cell><Data ss:Type="Number"><%= dupla.id %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.created_at %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.nombre %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.pais %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.registro_genealogico %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.raza %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.color %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.sexo %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.fecha_nacimiento %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.categoria %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.grado %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.tatuaje_microchip %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.especial_g1 %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.open_ac %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.ac_oficial %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.nombre %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.apellido %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.direccion %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.ciudad %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.pais %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.telefono %></Data></Cell>
          <Cell><Data ss:Type="String"><%= dupla.usuario.email %></Data></Cell>
          <% if dupla.guias.any? %>
            <Cell><Data ss:Type="String"><%= dupla.guias.first.nombre %></Data></Cell>
            <Cell><Data ss:Type="String"><%= dupla.guias.first.apellido %></Data></Cell>
            <Cell><Data ss:Type="String"><%= dupla.guias.first.direccion %></Data></Cell>
            <Cell><Data ss:Type="String"><%= dupla.guias.first.telefono %></Data></Cell>
            <Cell><Data ss:Type="String"><%= dupla.guias.first.email %></Data></Cell>
          <% end %>
        </Row>
        <% end %>
      </Table>
    </Worksheet>
</Workbook>

app/views/duplas/new.html.haml
- page_title!('Creando dupla')

#region-duplas.container.seccion

  .region
    .region-title
      %h1
        Creando
        %b
          dupla

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/duplas/show.html.haml
- page_title!(@dupla.nombre)
#region-duplas.container.seccion

  .region
    #duplas
      .region
        = render @dupla