config/routes.rb
Agilityperu::Application.routes.draw do

  resources :jueces

  get 'ubicacion/editar_ubicacion'

  put 'ubicacion/update_ubicacion'

  get '/ubicacion' => 'ubicacion#index'

  get 'tags/:tag', to: 'duplas#index', as: :tag

  resources :costos

  resources :reglamentos

  resources :guias

  resources :duplas

  resources :programas

  resources :organizadores

  resources :contactos

  resources :streamings

  resources :requisitos

  resources :transportes

  resources :hoteles

  resources :visas

  resources :mensajes

  resources :noticias

  resources :auspiciadores

  resources :slides

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  devise_for :usuarios, :controllers => { :registrations => "usuarios/registrations" }, :path => "usuarios", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  resources :usuarios do
    resources :duplas
  end

  root to: 'inicio#index'
  get "inicio/index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auspiciador.rb
class Auspiciador < ActiveRecord::Base
  mount_uploader :imagen, LogoUploader
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/dupla.rb
require 'csv'

class Dupla < ActiveRecord::Base

  default_scope  { order("created_at DESC") }

  mount_uploader :fotografia, FotografiaUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |dupla|
        csv << dupla.attributes.values_at(*column_names)
      end
    end
  end
  belongs_to :usuario
  has_many :guias
  accepts_nested_attributes_for :guias

  acts_as_taggable

  #paginates_per 5

  before_save :override_tag

  def override_tag
    self.tag_list << self.pais
  end
  validates :nombre, presence: true
  validates :registro_genealogico, presence: true
  validates :raza, presence: true
  validates :color, presence: true
  validates :categoria, presence: true
  validates :grado, presence: true
  validates :fotografia, presence: true



end

app/models/guia.rb
class Guia < ActiveRecord::Base

  belongs_to :dupla
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/juez.rb
class Juez < ActiveRecord::Base
  mount_uploader :foto, FotografiaUploader
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base

  validates :nombre, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
  validates :mensaje, presence: true

end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  mount_uploader :foto, FotoUploader

  default_scope  { order("fecha DESC") }

  def noticia_anterior
    self.class.first(:conditions => ["id < ?", id], :order => "id desc")
  end

  def siguiente_noticia
    self.class.first(:conditions => ["id > ?", id], :order => "id asc")
  end
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
end

app/models/programa.rb
class Programa < ActiveRecord::Base
end

app/models/reglamento.rb
class Reglamento < ActiveRecord::Base
end

app/models/requisito.rb
class Requisito < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :imagen, SlideUploader
end

app/models/streaming.rb
class Streaming < ActiveRecord::Base
end

app/models/transporte.rb
class Transporte < ActiveRecord::Base
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  mount_uploader :imagen1, FotografiaUploader
  mount_uploader :imagen2, FotografiaUploader
  mount_uploader :imagen3, FotografiaUploader
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :duplas

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :ciudad, presence: true
end

app/models/visa.rb
class Visa < ActiveRecord::Base
  mount_uploader :imagen, ImagenUploader
end

app/controllers/ubicacion_controller.rb
class UbicacionController < ApplicationController
  before_filter :authenticate_admin!, except:[:index]

  def index
    @ubicacion = Ubicacion.first
  end

  def editar_ubicacion
    @ubicacion = Ubicacion.first
  end

  def update_ubicacion
    @ubicacion = Ubicacion.first
    @ubicacion.update_attributes(ubicacion_params)
    if @ubicacion.save
      redirect_to ubicacion_path
    end
  end

      #person.update!(person_params)

  private

  def ubicacion_params
    params.require(:ubicacion).permit(:lugar, :direccion, :descripcion, :lat, :lng, :imagen1, :imagen2, :imagen3)
  end

end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/helpers/ubicacion_helper.rb
module UbicacionHelper

  def google_maps_api_key
    "AIzaSyDU-QXhZdMDOAQpKIaMwRmWGgjcDnTBZbA"
  end

  def google_api_url
    "https://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  end

  def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => google_api_access) do
    end
  end

end

app/views/ubicacion/_clima.html.erb
<a href="http://www.accuweather.com/en/pe/la-molina/1474990/weather-forecast/1474990" class="aw-widget-legal">
<!--
By accessing and/or using this code snippet, you agree to AccuWeather’s terms and conditions (in English) which can be found at http://www.accuweather.com/en/free-weather-widgets/terms and AccuWeather’s Privacy Statement (in English) which can be found at http://www.accuweather.com/en/privacy.
-->
</a><div id="awcc1393976130988" class="aw-widget-current"  data-locationkey="264120" data-unit="c" data-language="es" data-useip="false" data-uid="awcc1393976130988"></div><script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>

app/views/ubicacion/_mapa.html.erb
<div style='width: 100%;'>
  <div id="map_canvas" style='width: 100%; height: 500px;'></div>
</div>

app/views/ubicacion/editar_ubicacion.html.haml
= tinymce_assets
= tinymce
= form_for @ubicacion, url: ubicacion_update_ubicacion_path, method: :put, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @ubicacion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ubicacion.errors.count, "error")}"
      %ul
        - @ubicacion.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :lugar, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :lugar, class: 'form-control'
  .form-group
    = f.label :direccion, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :direccion, class: 'form-control'
  .form-group
    = f.label :descripcion, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :descripcion, class: 'tinymce', :rows => 15, :cols => 30
  .form-group
    = f.label :imagen1, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :imagen1, class: 'form-control'
  .form-group
    = f.label :imagen2, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :imagen2, class: 'form-control'
  .form-group
    = f.label :imagen3, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.file_field :imagen3, class: 'form-control'
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/ubicacion/index.html.haml
= google_maps_api

#region-ubicacion.container.seccion
  .region
    .region-title
      %h1= page_title!('Ubicación')

  .region
    - if current_admin
      = link_to 'Editar ubicacion', ubicacion_editar_ubicacion_path, class: 'btn btn-success'

#region-direccion.container.seccion
  .region
    %h3.titulos
      = image_tag image_path ('img-ubicacion.png')
      = @ubicacion.lugar

    %p
      = @ubicacion.direccion
    %p
      = @ubicacion.descripcion

  .region
    = image_tag @ubicacion.imagen1_url(:thumb) if @ubicacion.imagen1
    = image_tag @ubicacion.imagen2_url(:thumb) if @ubicacion.imagen2
    = image_tag @ubicacion.imagen3_url(:thumb) if @ubicacion.imagen3
  .region
    = render 'clima'

.map-wrapper
  = render 'mapa'