config/routes.rb
Agilityperu::Application.routes.draw do

  resources :jueces

  get 'ubicacion/editar_ubicacion'

  put 'ubicacion/update_ubicacion'

  get '/ubicacion' => 'ubicacion#index'

  get 'tags/:tag', to: 'duplas#index', as: :tag

  resources :costos

  resources :reglamentos

  resources :guias

  resources :duplas

  resources :programas

  resources :organizadores

  resources :contactos

  resources :streamings

  resources :requisitos

  resources :transportes

  resources :hoteles

  resources :visas

  resources :mensajes

  resources :noticias

  resources :auspiciadores

  resources :slides

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  devise_for :usuarios, :controllers => { :registrations => "usuarios/registrations" }, :path => "usuarios", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  resources :usuarios do
    resources :duplas
  end

  root to: 'inicio#index'
  get "inicio/index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auspiciador.rb
class Auspiciador < ActiveRecord::Base
  mount_uploader :imagen, LogoUploader
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/dupla.rb
require 'csv'

class Dupla < ActiveRecord::Base

  default_scope  { order("created_at DESC") }

  mount_uploader :fotografia, FotografiaUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |dupla|
        csv << dupla.attributes.values_at(*column_names)
      end
    end
  end
  belongs_to :usuario
  has_many :guias
  accepts_nested_attributes_for :guias

  acts_as_taggable

  #paginates_per 5

  before_save :override_tag

  def override_tag
    self.tag_list << self.pais
  end
  validates :nombre, presence: true
  validates :registro_genealogico, presence: true
  validates :raza, presence: true
  validates :color, presence: true
  validates :categoria, presence: true
  validates :grado, presence: true
  validates :fotografia, presence: true



end

app/models/guia.rb
class Guia < ActiveRecord::Base

  belongs_to :dupla
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/juez.rb
class Juez < ActiveRecord::Base
  mount_uploader :foto, FotografiaUploader
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base

  validates :nombre, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
  validates :mensaje, presence: true

end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  mount_uploader :foto, FotoUploader

  default_scope  { order("fecha DESC") }

  def noticia_anterior
    self.class.first(:conditions => ["id < ?", id], :order => "id desc")
  end

  def siguiente_noticia
    self.class.first(:conditions => ["id > ?", id], :order => "id asc")
  end
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
end

app/models/programa.rb
class Programa < ActiveRecord::Base
end

app/models/reglamento.rb
class Reglamento < ActiveRecord::Base
end

app/models/requisito.rb
class Requisito < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :imagen, SlideUploader
end

app/models/streaming.rb
class Streaming < ActiveRecord::Base
end

app/models/transporte.rb
class Transporte < ActiveRecord::Base
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  mount_uploader :imagen1, FotografiaUploader
  mount_uploader :imagen2, FotografiaUploader
  mount_uploader :imagen3, FotografiaUploader
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :duplas

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :ciudad, presence: true
end

app/models/visa.rb
class Visa < ActiveRecord::Base
  mount_uploader :imagen, ImagenUploader
end

app/controllers/streamings_controller.rb
class StreamingsController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:index]
  def permitted_params
    params.permit(:streaming => [:codigo_embed])
  end

  def create
    create!( notice: "Señal en vivo creada con éxito."){ streamings_path }
  end

  def update
    update!( notice: "La señal en vivo ha sido editada."){ streamings_path }
  end

  def destroy
    destroy!( notice: "La señal en vivo ha sido eliminada."){ streamings_path }
  end
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/helpers/streamings_helper.rb
module StreamingsHelper
end

app/views/streamings/_form.html.haml
= form_for @streaming, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @streaming.errors.any?
    #error_explanation
      %h2= "#{pluralize(@streaming.errors.count, "error")}"
      %ul
        - @streaming.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :codigo_embed, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :codigo_embed, class: 'form-control'
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/streamings/_player.html.erb
<div id="MediaPlayerTAB">
      <h1>Please Upgrade Your Flash Player</h1>
      <p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player"></a></p>
   </div>
   <script type="text/javascript" src="http://streamwowza.com/system/misc/flvplayer/swfobject.js"></script>
   <script type="text/javascript">

      var flashvars = {
       flvpFolderLocation: "http://streamwowza.com/system/misc/flvplayer/flvplayer/",
       flvpVideoSource: "rtmp://playerstreaming.net:1935/videoroncal,videoroncal",
       flvpWidth: "600",
       flvpHeight: "338",
       flvpAutoStartMovie: true
      };

      var params = {
       menu: "true",
       allowfullscreen: "true"
      };

      swfobject.embedSWF("http://streamwowza.com/system/misc/flvplayer/FLVplayer_Custom.swf", "MediaPlayerTAB", "640", "360", "9.0.0", "http://streamwowza.com//system/misc/flvplayer/expressInstall.swf", flashvars, params);
   </script>

app/views/streamings/_streaming.html.erb
<div id="MediaPlayerTAB">
   <h1>Please Upgrade Your Flash Player</h1>
   <p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player"></a></p>
</div>
<script type="text/javascript" src="http://streamwowza.com/system/misc/flvplayer/swfobject.js"></script>
<script type="text/javascript">
   
   var flashvars = {
    flvpFolderLocation: "http://streamwowza.com/system/misc/flvplayer/flvplayer/", 
    flvpVideoSource: "rtmp://playerstreaming.net:1935/videoroncal,videoroncal", 
    flvpWidth: "640", 
    flvpHeight: "360",
    flvpAutoStartMovie: true
   };
   
   var params = {
    menu: "true",
    allowfullscreen: "true"
   };

   swfobject.embedSWF("http://streamwowza.com/system/misc/flvplayer/FLVplayer_Custom.swf", "MediaPlayerTAB", "640", "360", "9.0.0", "http://streamwowza.com//system/misc/flvplayer/expressInstall.swf", flashvars, params);                     
</script>

app/views/streamings/edit.html.haml
- page_title!('Editando streaming')

#region-streamings.container

  .region
    .region-title
      %h1
        Editando
        %b
          streaming

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/streamings/index.html.haml
#region-streamings.container.seccion

  .region
    .region-title
      %h1= page_title!('Señal en Vivo')

    -# .region
      - if current_admin
        .admin-control
          = link_to 'Crear Señal en Vivo', new_streaming_path, class: 'btn btn-primary'

    %h3.titulos
      Disfruta del campeonato online.

    = render 'player'
    -# @streamings.each do |streaming|
      = link_to streaming.codigo_embed
      %br
        - if current_admin
          = link_to 'Editar', edit_streaming_path(streaming), class: 'btn btn-success'
          = link_to 'Eliminar', streaming, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/streamings/new.html.haml
- page_title!('Creando Señal en Vivo')

#region-streamings.container

  .region
    .region-title
      %h1
        Creando
        %b
          señal en vivo

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/streamings/show.html.haml
#region-streamings.container
  .region
    .region-title
      %h1= page_title!('streaming')

  .region
    %p
      %b Codigo embed:
      = @streaming.codigo_embed

  .region
    - if current_admin
      .admin-controls
        = link_to 'Editar', edit_streaming_path(@streaming), class: 'btn btn-success'
    = link_to 'Regresar', streamings_path, class: 'btn btn-warning'