config/routes.rb
Agilityperu::Application.routes.draw do

  resources :jueces

  get 'ubicacion/editar_ubicacion'

  put 'ubicacion/update_ubicacion'

  get '/ubicacion' => 'ubicacion#index'

  get 'tags/:tag', to: 'duplas#index', as: :tag

  resources :costos

  resources :reglamentos

  resources :guias

  resources :duplas

  resources :programas

  resources :organizadores

  resources :contactos

  resources :streamings

  resources :requisitos

  resources :transportes

  resources :hoteles

  resources :visas

  resources :mensajes

  resources :noticias

  resources :auspiciadores

  resources :slides

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  devise_for :usuarios, :controllers => { :registrations => "usuarios/registrations" }, :path => "usuarios", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  resources :usuarios do
    resources :duplas
  end

  root to: 'inicio#index'
  get "inicio/index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/auspiciador.rb
class Auspiciador < ActiveRecord::Base
  mount_uploader :imagen, LogoUploader
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/costo.rb
class Costo < ActiveRecord::Base
end

app/models/dupla.rb
require 'csv'

class Dupla < ActiveRecord::Base

  default_scope  { order("created_at DESC") }

  mount_uploader :fotografia, FotografiaUploader

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |dupla|
        csv << dupla.attributes.values_at(*column_names)
      end
    end
  end
  belongs_to :usuario
  has_many :guias
  accepts_nested_attributes_for :guias

  acts_as_taggable

  #paginates_per 5

  before_save :override_tag

  def override_tag
    self.tag_list << self.pais
  end
  validates :nombre, presence: true
  validates :registro_genealogico, presence: true
  validates :raza, presence: true
  validates :color, presence: true
  validates :categoria, presence: true
  validates :grado, presence: true
  validates :fotografia, presence: true



end

app/models/guia.rb
class Guia < ActiveRecord::Base

  belongs_to :dupla
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/juez.rb
class Juez < ActiveRecord::Base
  mount_uploader :foto, FotografiaUploader
end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base

  validates :nombre, presence: true
  validates :telefono, presence: true
  validates :email, presence: true
  validates :mensaje, presence: true

end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  mount_uploader :foto, FotoUploader

  default_scope  { order("fecha DESC") }

  def noticia_anterior
    self.class.first(:conditions => ["id < ?", id], :order => "id desc")
  end

  def siguiente_noticia
    self.class.first(:conditions => ["id > ?", id], :order => "id asc")
  end
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
end

app/models/programa.rb
class Programa < ActiveRecord::Base
end

app/models/reglamento.rb
class Reglamento < ActiveRecord::Base
end

app/models/requisito.rb
class Requisito < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :imagen, SlideUploader
end

app/models/streaming.rb
class Streaming < ActiveRecord::Base
end

app/models/transporte.rb
class Transporte < ActiveRecord::Base
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  mount_uploader :imagen1, FotografiaUploader
  mount_uploader :imagen2, FotografiaUploader
  mount_uploader :imagen3, FotografiaUploader
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :duplas

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :direccion, presence: true
  validates :telefono, presence: true
  validates :ciudad, presence: true
end

app/models/visa.rb
class Visa < ActiveRecord::Base
  mount_uploader :imagen, ImagenUploader
end

app/controllers/costos_controller.rb
class CostosController < InheritedResources::Base
  before_filter :authenticate_admin!, except: [:index]
  def permitted_params
    params.permit(:costo => [:titulo, :contenido])
  end

  def create
    create!( notice: "Costo creado con éxito."){ costos_path }
  end

  def update
    update!( notice: "El costo ha sido editado."){ costos_path }
  end

  def destroy
    destroy!( notice: "El costo ha sido eliminado."){ costos_path }
  end
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/guias_helper.rb
module GuiasHelper
end

app/views/costos/_form.html.haml
= tinymce_assets
= tinymce
= form_for @costo, :html => { class: 'form-horizontal', role: 'form' } do |f|
  - if @costo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@costo.errors.count, "error")}"
      %ul
        - @costo.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :titulo, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :titulo, class: 'form-control'
  .form-group
    = f.label :contenido, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :contenido, class: 'tinymce', :rows => 15, :cols => 30
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/costos/edit.html.haml
- page_title!('Editando costo')

#region-costos.container

  .region
    .region-title
      %h1
        Editando
        %b
          costo

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/costos/index.html.haml
#region-costos.container.seccion

  .region
    .region-title
      %h1= page_title!('costos')

    .region
      - if current_admin
        .admin-control
          = link_to 'Crear Costo', new_costo_path, class: 'btn btn-primary'


    - @costos.each do |costo|
      %h3.titulos
        = costo.titulo
      .descripcion
        = raw(costo.contenido)
      - if current_admin
        = link_to 'Editar', edit_costo_path(costo), class: 'btn btn-success'
        = link_to 'Eliminar', costo, :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-danger'

app/views/costos/new.html.haml
- page_title!('Creando costo')

#region-costos.container

  .region
    .region-title
      %h1
        Creando
        %b
          costo

  .region
    = render 'form'

  .region
    .admin-controls
      = link_to 'Regresar', 'javascript:history.back(-1)', class: 'btn btn-warning'

app/views/costos/show.html.haml
#region-costos.container
  .region
    .region-title
      %h1= page_title!('costo')

  .region
    %p
      %b Titulo:
      = @costo.titulo
    %p
      %b Contenido:
      = raw(@costo.contenido)

  .region
    - if current_admin
      .admin-controls
        = link_to 'Editar', edit_costo_path(@costo), class: 'btn btn-success'
    = link_to 'Regresar', costos_path, class: 'btn btn-warning'